
---
- name: Configure Windows 11 Server
  hosts: all
  tasks:
    - name: Install Active Directory Domain Services
      win_feature:
        name: AD-Domain-Services
        state: present

    - name: Install DNS Server
      win_feature:
        name: DNS
        state: present

    - name: Install Group Policy Management
      win_feature:
        name: GPMC
        state: present

    - name: Ensure Event Viewer is available
      win_feature:
        name: RSAT-EventLog-Viewer
        state: present
